apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: recruitment-vhigher
  namespace: hrteam
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.0
  storage:
    size: 256Mi
  bootstrap:
    initdb:
      import:
        type: microservice
        databases: ["app_db"]
        source:
          externalCluster: recruitment-source-18
  externalClusters:
    - name: recruitment-source-18
      connectionParameters:
        host: recruitment-rw.hrteam.svc
        user: streaming_replica
      password:
        name: recruitment-app
        key: password

  postgresql:
    parameters:
      wal_level: logical
