apiVersion: postgresql.cnpg.io/v1
kind: Subscription
metadata:
  name: recruitment-sub
  namespace: hrteam
  labels:
    # Optional: Match your existing Flux labels
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
spec:
  # The cluster that RECEIVES the data
  cluster:
    name: recruitment-vhigher
  # The database inside the target cluster
  dbname: app
  # The name of the subscription inside PostgreSQL
  name: recruitment_subscription
  # This must match the 'name' under 'externalClusters' in your recruitment-vhigher manifest
  externalClusterName: recruitment-source-18
  # This must match 'spec.name' from your Publication (recruitment-pub)
  publicationName: recruitment_publication
  # Optional: Ensure it starts replicating immediately
  enabled: true
